### ISSUE TITLE
江丰的这个软件有linux版的吗

### ISSUE THREAD

**Issue by Gaodelike** [tcmyxc/kfb2svs#1]
如题

**Comment by tcmyxc** [comment]
我暂时没有找到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月2日(周四) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tcmyxc/kfb2svs] 江丰的这个软件有linux版的吗 (Issue #1)




 
如题

**Comment by Rainydu184** [comment]
同问啊！

**Comment by tcmyxc** [comment]
你好，我是徐文祥。邮件已收到，我会在收到邮件的三个工作日中给你回复。
